# Generated by Django 5.0.6 on 2024-11-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_embarque', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(max_length=100)),
                ('exportador', models.CharField(max_length=200)),
                ('importador', models.CharField(max_length=200)),
            ],
        ),
    ]
