# Generated by Django 5.0.6 on 2024-11-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaniaPublicitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resultado', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('respuestas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionRedesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_programada', models.DateTimeField()),
                ('plataforma', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], max_length=50)),
            ],
        ),
    ]
