# Generated by Django 5.0.6 on 2024-11-13 23:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Embarques', '0001_initial'),
        ('Reportes', '0002_embarque_producto_transportista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('exitoso', models.BooleanField()),
                ('mensaje', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='transportista',
        ),
        migrations.AlterField(
            model_name='reporte',
            name='embarque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='Embarques.embarque'),
        ),
        migrations.RenameField(
            model_name='reporte',
            old_name='acciones',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='reporte',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='Reportes.loginactivity'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Transportista',
        ),
        migrations.DeleteModel(
            name='Embarque',
        ),
    ]
