# Generated by Django 5.0.6 on 2024-11-13 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Embarques', '0001_initial'),
        ('Reportes', '0003_loginactivity_remove_embarque_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_reportes', to='Reportes.loginactivity'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='embarque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embarque_reportes', to='Embarques.embarque'),
        ),
    ]
